server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:

        - id: cms-route #广告服务路由
          uri: lb://u-content
          predicates:
            - Path=/content/**
          filters:
            - RewritePath=/(?<segment>.*),/$\{segment}

        - id: qms-route # 题目微服务路由
          uri: lb://u-question
          predicates:
            - Path=/question/**
          filters:
            - RewritePath=/(?<segment>.*),/$\{segment}

        - id: ums-route # 用户微服务路由
          uri: lb://u-member
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/(?<segment>.*),/$\{segment}

#        - id: renrenfast-route # 人人后台服务路由
#          uri: lb://renren-fast
#          predicates:
#            - Path=/renren-fast/**
#          filters:
#            - RewritePath=/renren-fast/(?<segment>.*),/renren-fast/$\{segment}
#

        - id: qms-route # 题目微服务路由
          uri: lb://u-question
          predicates:
            - Path=/api/question/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: renrenfast-route # 人人后台服务路由
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}